#!/usr/bin/execlineb -P
foreground { if -n -t { test -d /var/log/exim } install -d -m 0755 -o s6log -g s6log /var/log/exim }
foreground { if -n -t { test -f /var/log/exim/mainlog } touch /var/log/exim/mainlog }
foreground { chown exim:exim /var/log/exim/mainlog }
envfile /etc/s6/sv/exim-log/conf
importas -sCiu DIRECTIVES DIRECTIVES
s6-setuidgid s6log exec -c s6-log -d3 -b -- ${DIRECTIVES} /var/log/exim
